import React from 'react';
// import serviceVector from "../../assets/images/landingPage/landingServiceVector.jpeg";

import PasswordStrengthAnalyzer from '../../layouts/landingPage/Password';

import Landingheader from '../../layouts/landingPage/landingHeader';
// import { LandingService } from '../../layouts/landingPage/landingservice';
// import LadingFeatures from '../../layouts/landingPage/LandingFeatures';
// import LandingTophackathon from '../../layouts/landingPage/LandingTopHackathon';
import { LandingFaq } from '../../layouts/landingPage/LandingFaq';
const HomePage = () => {
    return (
        <div>
            
            <Landingheader/>

            <PasswordStrengthAnalyzer/>
            
            {/* <LandingService
                heading="Unlock Your Potential with Our DevMatch"
                description="Our platform connects innovative minds with exciting opportunities. Whether you're hosting a hackathon or participating, you'll find invaluable resources and a supportive community."
                buttons={[
                    { title: "Apply for hackathon", variant: "primary", onClick: () => (window.location.href = '/hackathon') },
                    { title: "Find Partner", variant: "secondary", onClick: () => (window.location.href = '/FindPartner')},
                    { title: "Apply for Project", variant: "primary", onClick: () => (window.location.href = '/project') },
                    { title: "Find Exiting Events", variant: "secondary", onClick: () => (window.location.href = '/FindPartner')},
                ]}
                image={{
                    src: serviceVector,
                    alt: "Custom Image Alt Text",
                }}
            /> */}
            {/* <LandingTophackathon /> */}
            {/* <LadingFeatures /> */}
           
            <LandingFaq
    heading="Frequently Asked Questions"
    description="Find answers to common questions about our platform and services."
    footerHeading="Have more questions?"
    footerDescription="Reach out to our support team for assistance."
    button={{
        title: "Contact Support",
        variant: "secondary",
        onClick: () => (window.location.href = '/ContactUs'),
    }}
    questions={[
        {
            title: "What is the most secure password?",
            answer: "There’s no one password that is the “most secure”, and if there was, to write it here would make it insecure, as thousands of people would use it on their accounts. Rather, secure passwords contain a seemingly random combination of numbers, letters and symbols and include at least 16 to 20 characters."
        },
        {
            title: "What is an example of a secure password?",
            answer: "An example of a secure password is bL8%4TO&t9b%, generated by the password manager LastPass, which would take a computer 46 million years to crack!"
        },
        {
            title: "How secure is a 12 character password?",
            answer: "A 12 character password is somewhat secure; however, the most secure passwords are 16 to 20 characters long."
        },
        {
            title: "Are long passwords more secure?",
            answer: "Long passwords are more secure than short passwords. We recommend using passwords that are anywhere from 16 to 20 characters long, although nearly half of Americans use passwords of eight characters or fewer."
        },
        // {
        //     title: "How can I find a partner for a hackathon or project?",
        //     answer: "Use the 'Find Partner' section to post your requirements, such as skillsets or availability, or browse other users' posts to connect with potential partners."
        // },
        // {
        //     title: "Can hackathon organizers review and manage participant applications?",
        //     answer: "Yes, hackathon organizers can review participant applications and communicate with applicants directly from their dashboard."
        // },
        
        // {
        //     title: "Is there a way to promote my hackathon or project to reach more participants?",
        //     answer: "Yes, you can use the platform's promotional features to highlight your hackathon or project on the homepage or through targeted notifications."
        // },
        
    ]}
/>

        </div>
    );
};

export default HomePage;
